config/routes.rb
Rails.application.routes.draw do

  root                                 to: 'sessions#show'
  get     '/auth/:provider/callback',  to: 'sessions#create'
  delete '/logout',                    to: 'sessions#destroy'
  get   '/sign_in_with_github',        to: 'sessions#new'

  namespace :admin do
  #   resources :census_users, only: [:index]
     resources :weeks, only: [:new, :create, :edit, :update]
     resources :dashboard, only: [:index]
     resources :winners, only: [:index, :new, :create, :show]
   end

  namespace :user do
    resources :goals
  end
  put 'goals/:id/inc', to: 'goals#increment', as: 'inc_goal'

  resources :goals, only: [:index]
  resources :weeks, only: [:index, :create]
  resources :users, only: [:edit, :update, :show]
  resources :mods, only: [:index]
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::BaseController

  def index
    @mods = Mod.all
    @incomplete_mods = Mod.incomplete_mods
    if current_week
      @current_mod = current_week.mod
    else
      @current_mod = Mod.most_recent
    end
    @current_week_achievers = User.achievers(current_week)
  end

end

app/views/admin/dashboard/_mod_winner.html.erb
<h3>Students on track so far this Mod:</h3>
  <% @current_mod.mod_winners.each do |winner| %>
  <%= winner %><br>
  <% end %><br>
  <b><%= button_to "Past Mod Winners", mods_path, class: "btn btn-custom", method: :get%></b><br>
<hr>

app/views/admin/dashboard/_set_weeks.html.erb
<h1>Set weeks</h1><hr>

<%= form_tag weeks_path  do %>

  <%= label_tag :mod_id, "Mod" %>
  <%= select_tag :mod_id, options_from_collection_for_select(@incomplete_mods, "id", "inning") %><br><br>

  <%= label_tag :number_of_weeks %>
  <%= select_tag :number_of_weeks, options_for_select(1..6) %><br><br>

  <%= label_tag :start_date %>
  <%= date_field_tag :start_date %><br><br>

  <%= submit_tag "Create Weeks", class: 'btn btn-custom'%>
<% end %>
<hr>

app/views/admin/dashboard/_weekly_winner.html.erb
<%= form_tag admin_winners_path  do %>

    <%= label_tag :week_id %>
    <%= select_tag :week_id, options_from_collection_for_select(@mods.weeks_without_winners, "id", "start_date")%><br><br>

    <%= submit_tag "Select a winner!", class: 'btn btn-custom'%>
<% end %>

app/views/admin/dashboard/index.html.erb
<hr>
  <div>
    <%= link_to "Past goals", user_path(current_user) %> &nbsp;
    <%= link_to "Turing Totals", goals_path %> &nbsp;&nbsp;
    <%= link_to "Calendar", weeks_path %>
  <span>
    <%= image_tag('schedule-reminder.svg', size: '18x18') %>
    <%= link_to "Sign up for text reminders", edit_user_path(current_user) %>&nbsp;&nbsp;
  </span>
  </div>
  <hr>

<div class="container">
  <h2>Welcome, <%= current_user.name %></h2><br><br>
  <ul class="nav nav-tabs">
    <li class="active"><a data-toggle="tab" href="#current"><%= image_tag("http://i.imgur.com/UB6HRei.png", size:"50x50") %>&nbsp;Current Mod</a></li>
    <li><a data-toggle="tab" href="#set-weeks"><%= image_tag("http://i.imgur.com/Ako3axd.png", size:"50x50") %>&nbsp;Set Weeks</a></li>
    <li><a data-toggle="tab" href="#week-winners"><%= image_tag("http://i.imgur.com/97Ommhs.png", size:"50x50") %>&nbsp;Weekly Winners</a></li>
    <li><a data-toggle="tab" href="#mod-winners"><%= image_tag("http://i.imgur.com/Sth6Wis.png", size:"50x50") %>&nbsp;Mod Winners</a></li>
    <!-- <li><a data-toggle="tab" href="#cohorts"><%#= image_tag("http://i.imgur.com/3UKZnCg.png", size:"50x50") %>&nbsp;Cohorts</a></li> -->
  </ul>

  <div class="tab-content">
    <div id="current" class="tab-pane fade in active">
      <% if current_week %>
        <h1>This is <%=current_week.week_number.name%> of <%= @current_mod.inning %></h1>
        <h3><%= current_week.format_start_date %>-<%= current_week.format_end_date %></h3><hr>
        <% @current_mod.weeks.each do |week| %>
        <div><h5><%= week.week_number.name %>: <%= week.format_start_date %>-<%= week.format_end_date %></h5></div>
        <% end %>
      <% else %>
        <h1>This is INTERMISSION WEEK! </h1>
      <% end %>

      <hr>
    </div>
    <div id="set-weeks" class="tab-pane fade">
      <%= render partial: "set_weeks" %>
    </div>
    <div id="week-winners" class="tab-pane fade">
      <h1>Weekly Winners</h1><hr>
      <h3>Random weekly winner:</h3>
      <%= render partial: "weekly_winner" %>
      <hr>
      <h3>Achieved 100% of goals this week:</h3>
      <% @current_week_achievers.each do |achiever| %>
      <div><h4><%= achiever.name %>, <%= achiever.cohort %></h4></div>
      <% end %>
      <hr>
      <h3>This Mod's Weekly Winners:</h3>
      <% @current_mod.weeks.each do |week| %>
          <% if week.winner.is_a? Winner  %>
            <div><h4><%= week.week_number.name %>: <%= week.winner.user.name %>, <%= week.winner.user.cohort %></h4></div>
          <% else %>
          <div><h4><%= week.week_number.name %>: No winner selected yet</h4></div>
          <% end %>
      <% end %>
      <hr>
    </div>
    <div id="mod-winners" class="tab-pane fade">
      <h1>Mod Winners</h1>
      <hr>
      <%= render partial: "mod_winner" %>

    </div>
    <!-- <div id="cohorts" class="tab-pane fade">
      <h1>Cohorts</h1>
    </div> -->
  </div>
</div>