config/routes.rb
Rails.application.routes.draw do

  root                                 to: 'sessions#show'
  get     '/auth/:provider/callback',  to: 'sessions#create'
  delete '/logout',                    to: 'sessions#destroy'
  get   '/sign_in_with_github',        to: 'sessions#new'

  namespace :admin do
  #   resources :census_users, only: [:index]
     resources :weeks, only: [:new, :create, :edit, :update]
     resources :dashboard, only: [:index]
     resources :winners, only: [:index, :new, :create, :show]
   end

  namespace :user do
    resources :goals
  end
  put 'goals/:id/inc', to: 'goals#increment', as: 'inc_goal'

  resources :goals, only: [:index]
  resources :weeks, only: [:index, :create]
  resources :users, only: [:edit, :update, :show]
  resources :mods, only: [:index]
end

app/models/goal.rb
class Goal < ApplicationRecord
  belongs_to :category
  belongs_to :user
  belongs_to :week

  validates :description, :category_id, :user_id, :week_id, :total_goal_count, presence: true


  def self.community_progress(week_id, category_id)
      where(week_id: week_id).where(category_id: category_id).map { |goal| goal.progress_count }.reduce(:+)
  end

  def self.community_total(week_id, category_id)
    where(week_id: week_id).where(category_id: category_id).map { |goal| goal.total_goal_count }.reduce(:+)
  end

  def achieved?
    total_goal_count == progress_count
  end

end

# <><><>If Goals become restricted to ONLY 7 TOTAL per category, use these methods<><><>

# def all_category_totals
#   user.goals.where(category: category).pluck(:total_goal_count)
# end
# #
# def category_total
#   all_category_totals.reduce(:+)
# end
#
# def reasonable_total?(new_total)
#   if all_category_totals.empty?
#     new_total.to_i <= 7
#   else
#     pre_update_total = category_total - total_goal_count
#     post_update_total = pre_update_total + new_total.to_i
#
#     post_update_total <= 7
#   end
# end

app/models/user.rb
class User < ApplicationRecord
  has_many :goals, dependent: :destroy
  has_many :weeks, through: :goals
  has_many :winners

  enum role: %w(default admin)

  validates :github_id, presence: true
  validates :phone_number, presence: true, if: :wants_reminder?

  scope :text_recipients, -> { where(wants_reminder: true) }

  after_update :send_confirmation_message, if: -> { self.wants_reminder? && (wants_reminder_changed? || phone_number_changed?) }


  def send_confirmation_message
    Reminder.send_confirmation_message(self)
  end
  def sanitize_phone_number
    phone_number.gsub(/-/, '').prepend("+1")
  end

  def weekly_progress(week_id)
     goals.where(week_id: week_id).map {|goal| goal.progress_count }.reduce(:+)
  end
  def weekly_total_achieved(week_id)
     goals.where(week_id: week_id).map {|goal| goal.total_goal_count }.reduce(:+)
  end

  def achieved_all_goals_this_week?(week_id)
    goals.where(week_id: week_id).count > 0 && weekly_progress(week_id) == weekly_total_achieved(week_id)
  end

  def self.achievers(week_id)
    achievers = []
    all.each do |x|
      if x.achieved_all_goals_this_week?(week_id)
        achievers << x
      end
    end
   achievers
  end

  def self.select_weekly_winner(week_id)
    User.achievers(week_id).shuffle.pop
  end

end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController

  def index
    @categories = Category.all
  end

  def increment
    @goal = current_user.goals.find(params[:id])
    new_count = @goal.progress_count + 1

    if @goal.update(progress_count: new_count)
      render json: {progress_count: @goal.progress_count, total_goal_count: @goal.total_goal_count}.to_json
    else
      flash.now[:danger] = 'Unable to increment goal.'
      redirect_to user_goals_path
    end
  end

end

app/controllers/user/goals_controller.rb
class User::GoalsController < ApplicationController
  before_action :set_goal, only: [:show, :edit, :destroy]
  before_action :set_user, only: [:create, :update, :increment]

  def index
    if current_week
      @goals = current_user.goals.where(week_id: current_week.id).order(:created_at)
    else
      @goals = current_user.goals 
    end
  end

  def show
  end

  def new
    @goal = Goal.new
  end

  def edit
    @goal = current_user.goals.find(params[:id])
  end

  def create
    @goal = current_user.goals.new(goal_params)
    new_total = goal_params[:total_goal_count]

    # if @goal.reasonable_total?(new_total) && @goal.save
    if @goal.save && new_total.to_i <= 7
      flash[:success] = "Goal was successfully created."
      redirect_to user_goals_path
    else
      flash.now[:danger] = "#{@goal.errors.messages.first[0]} #{@goal.errors.messages.first[1][0]}"
      render :new
    end
  end


  def update
    @goal = current_user.goals.find(params[:format])
    @goal.update(goal_params)
    new_total = goal_params[:total_goal_count]

    # if @goal.reasonable_total?(new_total) && @goal.update(goal_params)
    if new_total.to_i <= 7 && @goal.save
      flash.now[:success] = 'Goal was successfully updated.'
      redirect_to user_goals_path
    else
      flash.now[:danger] = "#{@goal.errors.messages.first[0]} #{@goal.errors.messages.first[1][0]}"
      render :edit
    end
  end

  def destroy
    @goal.destroy
    flash.now[:success] = "Goal Successfully Deleted!"
    redirect_to user_goals_path
  end

  private
    def set_user
      @user = current_user
    end

    def set_goal
      @goal = current_user.goals.find(params[:id])
    end

    def goal_params
      params.require(:goal).permit(:description,
                                   :total_goal_count,
                                   :category_id).merge(week: current_week)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @goals = current_user.goals.where.not(week_id: current_week.id).order(week_id: :desc)
  end

  def edit
  end

  def update
    current_user.update(user_params)

    if current_user.save
      flash[:success] = 'Account updated.'
      redirect_to user_goals_path
    else
      flash.now[:danger] = "#{current_user.errors.messages.first[0]} #{current_user.errors.messages.first[1][0]}"
      render :edit
    end

  end

  private
  def user_params
    params.require(:user).permit(:name, :cohort, :phone_number, :wants_reminder)
  end
end

app/views/user/goals/_form.html.erb
<%= form_for([current_user, @goal]) do |f| %>

<div class="form">

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :total_goal_count %>
    <%= f.number_field :total_goal_count, min: 1, max: 7 %>
  </div>

  <% if @goal.new_record? %>
    <div class="field">
      <%= f.label :category_id %>
      <%= f.collection_select :category_id, Category.all, :id, :name, :required => true, :include_blank => "Select a Category" %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit class: 'btn btn-custom'%>
  </div>
<% end %>
</div>

app/views/user/goals/edit.html.erb
<h1>Edit your goal</h1>

<%= render 'form'%>

app/views/user/goals/index.html.erb
<hr>
  <div>
    <%= link_to "Past goals", user_path(current_user) %> &nbsp;
    <%= link_to "Turing Totals", goals_path %> &nbsp;&nbsp;
    <%= link_to "Calendar", weeks_path %>

    <span>
      <%= image_tag('schedule-reminder.svg', size: '18x18') %>
      <%= link_to "Sign up for text reminders", edit_user_path(current_user) %>&nbsp;&nbsp;
    </span>
  </div>
<hr>

<% if current_week %>
<section class="user-goals">
  <article class="week-date-display">
    <h2><%= current_week.week_number.name %></h2>
    <h4 class="day-date"><%= current_week.format_start_date %> - <%= current_week.format_end_date %></h4>
  </article>

  <% @goals.each do |goal| %>
    <article class="goal-first-row">
      <div class="goal_<%= goal.category.name %>">
        <%#= ## CATEGORY ICON %>
        <div class='goal-title-icon'>
          <img class='icons' src= "<%= goal.category.image_path%>"> &nbsp;
          <h3><%= goal.description %></h3>
        </div>
          <%= link_to 'Edit', edit_user_goal_path(goal) %>
          <%= link_to 'Delete', user_goal_path(goal), method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>

      <div class="goal-second-row">
        <% if  goal.achieved? %>
        <div class="icons">
          <%= image_tag("http://i.imgur.com/f7s3dQN.png", size:"30x30") %>
        </div>
        <% else  %>
        <div class='plus-sign' id="<%=goal.id%>">
          <%= image_tag('plus_sign.png', size: '28x28', class: 'goal-inc', id: goal.id) %>
        </div>
        <% end %>

       <div class="progress">

        <div id="cat-<%=goal.category_id%>" goal-id="<%=goal.id%>" class="progress-bar" role="progressbar" style="width:  <%= ((goal.progress_count / goal.total_goal_count.to_f) * 100).round%>%;" aria-valuenow="<%= ((goal.progress_count / goal.total_goal_count.to_f) * 100).round%>" aria-valuemin="0" aria-valuemax="100"></div>
        </div>

      <h4><%= goal.progress_count %>/<%= goal.total_goal_count %></h4>
      </div>

    <div class="divider"></div>
    </article>
    <hr>
    <% end %>
  </section>
  <br>
  <%= link_to 'New Goal', new_user_goal_path, class: 'btn btn-danger' %>

<% else %>
  <section class="user-goals">
    <article class="week-date-display">
      <h2>Enjoy Intermission Week!</h2>
    </article>
  </section>
<% end %>

app/views/user/goals/new.html.erb
  <div class="row">
    <div class="col">

      <details class='instructions' close >
        <!-- <span class="glyphicon glyphicon-list" aria-hidden="true"> </span> -->
        <summary><b>Goal Setting Instructions</b></summary>
          <ul>
            <p> <%=image_tag("checkmark.png", size: '30x30')%>
              Your goals are your own. You may set as many (or as few) goals as you like. Only you will know what your actual goals are. </p>

              <p> <%=image_tag("checkmark.png", size: '30x30')%>Each week you choose to set goals, your total progress will be included in the Turing Community's weekly totals.</p>

            <p><%=image_tag("checkmark.png", size: '30x30')%>Each goal should be different. You must choose a category for each goal. You can have more than one goal for each category.</p>

            <p><%=image_tag("checkmark.png", size: '30x30')%>You set the number of times you will meet your goal within the week (with a max of 7, once for each day). The number of goals and count only matter for you. </p>

            <p><%=image_tag("checkmark.png", size: '30x30')%>If you achieve 100% of your goals, you are eligible for a weekly prize. Weekly winners are randomly chosen from all students who have achieved 100% of their goals.</p>

            <p><%=image_tag("checkmark.png", size: '30x30')%>You may mark progress towards your goals through Sunday at midnight of each week. New goals can be set every Monday morning.</p>

            <p><%=image_tag("checkmark.png", size: '30x30')%>If you meet 100% of your goals every week throughout the entire mod you will receive a grand prize! </p>
          </ul>
      </details>
    </div>
  </div>
<br>

<%= render 'form', goal: @goal %>