config/routes.rb
Rails.application.routes.draw do

  root                                 to: 'sessions#show'
  get     '/auth/:provider/callback',  to: 'sessions#create'
  delete '/logout',                    to: 'sessions#destroy'
  get   '/sign_in_with_github',        to: 'sessions#new'

  namespace :admin do
  #   resources :census_users, only: [:index]
     resources :weeks, only: [:new, :create, :edit, :update]
     resources :dashboard, only: [:index]
     resources :winners, only: [:index, :new, :create, :show]
   end

  namespace :user do
    resources :goals
  end
  put 'goals/:id/inc', to: 'goals#increment', as: 'inc_goal'

  resources :goals, only: [:index]
  resources :weeks, only: [:index, :create]
  resources :users, only: [:edit, :update, :show]
  resources :mods, only: [:index]
end

app/models/week.rb
class Week < ApplicationRecord
  belongs_to :week_number
  belongs_to :mod
  has_many :goals
  has_many :users, through: :goals
  has_one :winner

  validates :start_date, :end_date, presence: true

  def self.set_weeks(num_of_weeks, weeks_start, mod_id)
    week_nums = [*1..num_of_weeks]
    starts_ends = {}
    start = weeks_start
    week_nums.each do |num|
      starts_ends[num] = [start, start+6]
      start +=7
    end
    starts_ends.each do |num, dates|
      Week.create(week_number_id: num, start_date: dates.first, end_date: dates.last, mod_id: mod_id)
    end
  end

  def self.get_start_dates
    all.map { |week| week.start_date}
  end

  def self.get_end_dates
    all.map { |week| week.end_date}
  end

  def self.order_by_created_at
    all.order(:created_at)
  end

  def format_start_date
    self.start_date.strftime("%B %e")
  end

  def format_end_date
    self.end_date.strftime("%e %Y")
  end

  def ended?
    self.end_date.past?
  end

end

app/controllers/admin/weeks_controller.rb
class Admin::WeeksController < ApplicationController
  
  def new
    @mods = Mod.all
  end

  def create
    @mods = Mod.all
    Week.set_weeks((params["number_of_weeks"].to_i), (params["start_date"].to_date), (params["mod_id"].to_i))

      redirect_to weeks_path
  end

  private

  def week_params(my_params)
    my_params.permit(:number_of_weeks, :start_date, :mod_id)
  end
end

app/controllers/weeks_controller.rb
class WeeksController < ApplicationController
  def index
    @weeks = Week.all
    @mods = Mod.all
  end

  def create
    @mods = Mod.all
    Week.set_weeks((params["number_of_weeks"].to_i), (params["start_date"].to_date), (params["mod_id"].to_i))

      redirect_to weeks_path
  end

  private

  def week_params(my_params)
    my_params.permit(:number_of_weeks, :start_date, :mod_id)
  end
end

app/views/admin/weeks/_form.html.erb
<%= form_tag admin_weeks_path  do %>

  <%= label_tag :mod_id, "Mod" %>
  <%= select_tag :mod_id, options_from_collection_for_select(@mods, "id", "inning") %><br><br>

  <%= label_tag :number_of_weeks %>
  <%= select_tag :number_of_weeks, options_for_select(1..6) %><br><br>

  <%= label_tag :start_date %>
  <%= date_field_tag :start_date %><br><br>

  <%= submit_tag "Create Weeks", class: 'btn btn-custom'%>
<% end %>

app/views/admin/weeks/index.html.erb
<div class='back'>
  <%= link_to "Admin Dashboard", admin_dashboard_index_path  %>
</div>

<h1>Weeks Index</h1>
<hr>

<% @mods.each do |mod| %>
  <h4><b>Mod <%= mod.inning %></b></h4>
    <% mod.weeks.each do |week|%>
      <p> <%= week.format_start_date %> - <%= week.format_end_date %></p>
      <% end %>
    <hr>
<% end %>

app/views/admin/weeks/new.html.erb
<h1>Create a week</h1>

<%= render partial: "form" %>