config/routes.rb
Rails.application.routes.draw do

  root                                 to: 'sessions#show'
  get     '/auth/:provider/callback',  to: 'sessions#create'
  delete '/logout',                    to: 'sessions#destroy'
  get   '/sign_in_with_github',        to: 'sessions#new'

  namespace :admin do
  #   resources :census_users, only: [:index]
     resources :weeks, only: [:new, :create, :edit, :update]
     resources :dashboard, only: [:index]
     resources :winners, only: [:index, :new, :create, :show]
   end

  namespace :user do
    resources :goals
  end
  put 'goals/:id/inc', to: 'goals#increment', as: 'inc_goal'

  resources :goals, only: [:index]
  resources :weeks, only: [:index, :create]
  resources :users, only: [:edit, :update, :show]
  resources :mods, only: [:index]
end

app/views/layouts/_navbar.html.erb
<nav>
  <%=image_tag("turing_logo_wellness.png", size: '90x90')%>
  <% if current_user %>
  <a class="app-title" href= "<%=user_goals_path%>">Wellness Tracker</a>
  <% end %>

<% if current_user %>
  <details close>
    <summary><%=current_user.name%> </summary>&nbsp;
      <p><% if current_user.admin? %>
        <%= link_to "Admin Dashboard", admin_dashboard_index_path  %>
      <% end %></p>

      <p><%= link_to "Edit profile", edit_user_path(current_user) %></p>
      <p><% if current_user %>
        <%= link_to "Logout", logout_path, method: :delete %></p>
      <% end %>
  </details>
<% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag 'turing_logo_wellness.png' %>
    <title>Turing Wellness Tracker</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed:300,400,700" rel="stylesheet">
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

    <%= render partial: 'layouts/navbar' %>

    <div class="flashes">
      <% flash.each do |type, message| %>
        <div class="alert alert-<%= type %>">
          <button type="button" class="close" data-dismiss='alert'>x</button>
          <%= sanitize(message) %>
      <% end %>
        </div>
    </div>


  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>